conditioning:
  method: ps
  params:
    scale: 2.0

data:
  name: ffhq
  # root: ./data/samples/
  root: ../facedata-preprocessed/

measurement:
  operator:
    name: motion_blur
    kernel_size: 61
    intensity: 0.5

  noise: 
    name: gaussian
    sigma: 0.0
