conditioning:
  method: ps_anneal
  params:
    scale: 0.3

data:
  name: ffhq
  # root: ./data/samples/
  root: ../data/ffhq256/

measurement:
  operator:
    name: motion_blur
    kernel_size: 61
    intensity: 0.5

  noise: 
    name: gaussian
    sigma: 0.0
