conditioning:
  method: ps_semantic
  params:
    scale: 1.0
    sem_guid_scale: 0.01
    do_anneal: True
    anneal_factor: 10.0
    norm_exp: 1

data:
  name: ffhq
  # root: ./data/samples/
  root: ../ref_images/

measurement:
  operator:
    name: motion_blur
    kernel_size: 61
    intensity: 0.5

  noise: 
    name: gaussian
    sigma: 0.05
