conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  # root: ./data/samples/
  root: ../data/ffhq256/

measurement:
  operator:
    name: nonlinear_blur
    opt_yml_path: ./bkse/options/generate_blur/default.yml

  noise: 
    name: gaussian
    sigma: 0.05
