conditioning:
  method: ps
  params:
    scale: 0.01
    sem_guid_scale: 0.0

data:
  name: ffhq
  # root: ./data/samples/
  root: ../ood_images_cropped/

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 4
  
  noise: 
    name: gaussian
    sigma: 0.05
