conditioning:
  method: ps_semantic
  params:
    scale: 1.0
    sem_guid_scale: 0.01
    do_anneal: True
    anneal_factor: 10.0
    norm_exp: 1

data:
  name: ffhq
  # root: ./data/samples/
  root: ../ref_images/

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 8

  noise: 
    name: gaussian
    sigma: 0.05
