conditioning:
  method: ps_semantic
  params:
    scale: 1.0
    sem_guid_scale: 1.0

data:
  name: ffhq
  # root: ./data/samples/
  root: ../facedata-preprocessed/

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 8
  
  noise: 
    name: gaussian
    sigma: 0.05
